about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('', views.about, name='about'),
    path('daftar/', views.question, name='question'),
    ]

form/urls.py
from django.urls import path, include
from form import views

app_name = 'form'

urlpatterns = [
    path('', views.buatLaporan, name='buatLaporan'),
]

frontpage/urls.py
from django.urls import path, include
from frontpage import views

app_name = 'frontpage'

urlpatterns = [
    path('', views.frontpage, name="beranda"),
    path('login/', views.register, name= "register")
]

laporan/urls.py
from django.urls import path, include
from laporan import views

app_name = 'laporan'

urlpatterns = [
    path('lihatLaporan/', views.lihatLaporan, name='lihatLaporan'),
    path('ubahLaporan/', views.ubahLaporan, name='ubahLaporan'),
    path('ubahLaporan/<int:id>', views.ubahStatusLaporan, name='ubahStatusLaporan'),
]

tk1/tk1/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontpage.urls')),
    path('laporan/', include('laporan.urls')),
    path('about/', include('about.urls')),
    path('buatLaporan/', include('form.urls'))
]

about/models.py
from django.db import models

class questionModel(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

form/models.py
from django.db import models

# Create your models here.
class Lapor(models.Model):
    nama = models.CharField(max_length=50)
    kontak = models.CharField(max_length=50)
    laporan = models.TextField()
    #bukti = models.FileField(upload_to=None)
    
    #Sambungin Models milik apps laporan
    status = models.ForeignKey('laporan.PilihStatus', on_delete=models.DO_NOTHING, default=1)
    

    def __str__(self):
        return self.nama

frontpage/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.user.username

laporan/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

STATUS = [('Diproses', 'Diproses'),
          ('Ditolak', 'Ditolak'),
          ('Selesai', 'Selesai')]

class PilihStatus(models.Model):
    status = models.CharField(max_length=50, choices=STATUS, default="---")

    #Agar memunculkan "value" dari statusnya
    def __str__(self):
        return self.status

about/forms.py
from django import forms
from .models import questionModel
from django.forms import ModelForm

class questionForm(forms.ModelForm):

    class Meta:
        model = questionModel
        fields = ['name', 'email', 'message']
        labels = {'name': 'Nama', 'email': 'E-mail', 'message': 'Pertanyaan'}
        widgets={
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'message': forms.Textarea(attrs={'class': 'form-control', 'rows':'4'})
        }

form/forms.py
from django import forms
from .models import Lapor


class BuatLaporan(forms.ModelForm):
    class Meta():
        model = Lapor
        fields = ['nama', 'kontak', 'laporan']
        

frontpage/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ['username', 'email', 'password']

laporan/forms.py
from django import forms
from form.models import Lapor
from django.forms import ModelForm

class FormPilihStatus(ModelForm):
    class Meta:
        model = Lapor
        fields = ['status']
        labels = {'status' : ''}
        widgets = {'status' : forms.Select(attrs={'class' : 'form-control'})}

about/views.py
from django.shortcuts import render, redirect
from .forms import questionForm
from .models import questionModel
from django.contrib import messages
from django.http import HttpResponseRedirect

def about(request):
    form=questionForm()        
    database = questionModel.objects.all()
    data = {'form':form, 'database': database}
    return render(request, 'about/about.html', data)

def question(request):
    
    if request.method == 'POST':
        form = questionForm(request.POST)
        if form.is_valid():
            fields=['name','email','message']
            form.save()

    return HttpResponseRedirect("/about")

form/views.py
from django.shortcuts import render, redirect
from .forms import BuatLaporan
from .models import Lapor
from . import forms
from django.http import HttpResponseRedirect

# Create your views here.
def buatLaporan(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = BuatLaporan(request.POST or None)
        # check whether it's valid:
        if form.is_valid():
            form.save()
            form = BuatLaporan()
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/buatLaporan/')
    
    # if a GET (or any other method) we'll create a blank form
    else:
        form = BuatLaporan()

    return render(request, 'form/buat_laporan.html', {'form':form})

frontpage/views.py
from django.shortcuts import render
from frontpage.forms import UserForm

# Create your views here.
def frontpage(request):
    return render(request, 'frontpage/frontpage.html')

def register(request):
    konten = {'form'  : UserForm}
    

    if request.method == "POST":
        user_form = UserForm(data= request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

    return render(request, 'frontpage/register.html', konten)

laporan/views.py
from django.shortcuts import render, redirect
from form.models import Lapor
from form.forms import BuatLaporan
from .forms import FormPilihStatus

# Create your views here.
def lihatLaporan(request):
    respon = Lapor.objects.all()
    konten = {'title' : 'Lihat Status Laporan', 'respon' : respon}
    return render(request, 'laporan/lihat_laporan.html', konten)

def ubahLaporan(request):
    respon = Lapor.objects.all()
    form = FormPilihStatus()
    konten = {'title' : 'Ubah Status Laporan', 'respon' : respon, 'lapor':form}
    return render(request, 'laporan/ubah_laporan.html', konten)

def ubahStatusLaporan(request, id):
    ubahStatus = Lapor.objects.get(pk=id)
    respon = Lapor.objects.all()
    form = FormPilihStatus(request.POST or None, instance=ubahStatus)
    if form.is_valid():
        ubahStatus = form.save(commit=False)
        ubahStatus.save()
        konten = {'title' : 'Ubah Status Laporan', 'form' : form, 'respon' : respon, 'ubahStatus' : ubahStatus}
        return redirect('/laporan/ubahLaporan')
    else:
        konten = {'title' : 'Ubah Status Laporan', 'form' : form, 'respon' : respon, 'ubahStatus' : ubahStatus}
        return redirect('/laporan/ubahLaporan')

templates/about/about.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %} Tentang Kami {% endblock title %}
{% block navbar-active-about %}active{% endblock navbar-active-about %}

<!-- tentang lapor-sis! -->
{% block content_block %}
<div class="fully blue">
    <div class="container ttg">
        <h1 class="tentang ttg-1"><span style='color: #f2858a'>Lapor</span><span style='color: #b1cbd8'>-sis!</span></h1>
    </div>
</div>

<!-- Lapor-sis merupakan -->
<div class="pink">
    <div class="container-fluid">
        <div class="row penjelasan">
            <div class="col-xl-6 col-sm-12 laporin">
                <p class="lapor"><b>Lapor-sis!</b> merupakan sebuah sarana pengaduan tindakan kekerasan 
                pada remaja dan anak-anak berbasis media sosial yang mudah 
                diakses dan terpadu dengan KOMNAS HAM, maupun kepolisian.</p>
                <br>
                <p class="lapor">Lapor-sis! diinisiasi dengan latar belakang banyaknya remaja maupun
                anak-anak yang mengalami tindak kekerasan namun tidak berani untuk melapor
                karena takut diremehkan, takut akan disalahkan, maupun alasan lainnya.</p>
                <br>
                <p class="lapor terakhir">Dengan adanya Lapor-sis!, korban tindakan kekerasan dapat melapor dengan
                mudah tanpa tatap muka. Lapor-sis! juga akan melaporkan pengaduan tidak langsung
                kepada kepolisian untuk pertama kalinya, melainkan melaporkan kepada pihak
                KOMNAS HAM terlebih dahulu, baru kemudian dengan bantuan KOMNAS HAM akan
                ditindaklanjuti ke kepolisian.</p>
            </div>
            <div class="col-xl-6 col-sm-12">
                <img src="{% static 'alur.png' %}" alt="alur kerja Lapor-Sis!" class="img-fluid">
            </div>
        </div>
    </div>
</div>
    
<!-- FAQ -->
<div class="blue">
    <div class="container-fluid">
        <div class="row tanya">
            <div class="col-12">
                <h1 class="font-tanya"> Daftar Pertanyaan </h1>
            </div>
        </div>
        <div class="row list">
            {% for all in database %}
                <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-xs-12 daftar">
                    <h5 class="white">Nama:</h5> 
                    <h5>{{ all.name }}</h5>                                                        
                    <h5 class="white">Pertanyaan: </h5>
                    <h5>{{ all.message }}</h5>                                                        
                    <h5 class="white">Jawaban: </h5>
                    <h5>Pending</h5>                                                        
                </div>
            {% endfor %}
            <br>
        </div>
    </div>
</div>

<!-- form -->
<!-- nama, email, pertanyaan, button submit -->
<div class="pink" id="form-ini">
    <div class="container-fluid">
        <div class="row tanya">
            <div class="col-12">
                <h1 class="font-tanya">Silakan Tanya Kami!</h1>
            </div>
        </div>
        <div class="row formnya">
            <div class="col-12">
                <form action="daftar/" method="POST">
                    {% csrf_token %}
                    <div>
                        <label>{{ form.name.label_tag }}</label> 
                        {{ form.name }}
                        <br>
                    </div>
                    <div>
                        <label>{{ form.email.label_tag }}</label>
                        {{ form.email }}
                        <br>
                    </div>
                    <div>
                        <label>{{ form.message.label_tag }}</label>
                        {{ form.message }}
                    </div>
                    <br>
                    <br>
                    <input type="submit" value="Kirim" style="float: right" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>
</div>

<!-- footer -->
<footer class="container-fluid text-center">
    <h6>Dikembangkan oleh</h6>
    <h5>KA16</h5>
</footer>

{% endblock content_block %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <!-- Meta Tag -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- BootstrapCDN CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href=" {% static 'css/frontpage.css' %}">
    <link rel="stylesheet" href=" {% static 'base.css' %}">
    <link rel="stylesheet" href=" {% static 'css/about.css' %}">
    <link rel="stylesheet" href=" {% static 'css/login.css' %}">

    <!-- BootstrapCDN JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <!-- Google Fonts -->

    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker&display=swap" rel="stylesheet"> 
    <!--  font-family: 'Permanent Marker', cursive; -->

    <link href="https://fonts.googleapis.com/css?family=Boogaloo&display=swap" rel="stylesheet"> 
    <!-- font-family: 'Boogaloo', cursive; -->

    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <!-- font-family: 'Montserrat', sans-serif; -->

    <link href="https://fonts.googleapis.com/css?family=Comfortaa&display=swap" rel="stylesheet"> 
    <!-- font-family: 'Comfortaa', cursive; -->

    <link href="https://fonts.googleapis.com/css?family=BenchNine&display=swap" rel="stylesheet"> 
    <!-- font-family: 'BenchNine', sans-serif; -->


    <title>{% block title %}{% endblock title %}</title>
</head>
<body>  
    <nav class="navbar navbar-expand-md container-navbar navbar-dark mx-auto ">
        <a href="/" class="navbar-brand mr-5 ml-2" id="logo">Lapor<span style="color: #b7d2e0">-sis!</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mr-auto">
                <a href="/" class="nav-link nav-item button-nav {% block navbar-active-home %}{% endblock navbar-active-home %}">Beranda</a>
                <a href="{% url 'form:buatLaporan' %}" class="nav-link nav-item button-nav {% block navbar-active-buat %}{% endblock navbar-active-buat %}">Buat Laporan</a>
                <a href="{% url 'laporan:lihatLaporan' %}" class="nav-link nav-item button-nav {% block navbar-active-status %}{% endblock navbar-active-status %}">Status Laporan</a>
                <a href="{% url 'about:about' %}" class="nav-link nav-item button-nav {% block navbar-active-about %}{% endblock navbar-active-about %}">Tentang Kami</a>
            </ul>
            <div clas="navbar-nav">
                <a href="{% url 'frontpage:register' %}" class="nav-item nav-link button-nav btn btn-primary mt-2 mt-md-0">Daftar Newsletter</a>
            </div>
        </div>
    </nav>
    {% block content_block %}{% endblock content_block %}
</body>
</html>

templates/form/buat_laporan.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load staticfiles %}
{% block navbar-active-buat %}active{% endblock navbar-active-buat %}

{% block content_block %}
<div id="buat_laporan">
    <div class="container-fluid">
        <h1 style="text-align: center; margin: 25px;">Ceritakan Masalahmu Disini!</h1>
        <div class="row" style="margin: auto;">
            <div class="col-sm-6">
                <form method="POST">
                    <table> {% csrf_token %}
                        {{ form }}
                    </table>
                    <div class="row" style="margin-top: 30px;">
                        <div class="col-sm-5"></div>
                        <input type="submit" value="Lapor-sis!" class="col-sm-2"/>
                    </div>
                </form>
            </div>
            <div class="col-sm-6" style="text-align: center;">
                <br><br><br><br><br><br>
                <i>“Marilah kita bersama menjaga perempuan serta anak yang ada di sekitar kita,
                    anak merupakan generasi penerus bangsa dan menyelamatkan satu perempuan sama dengan menyelamatkan satu bangsa."</i>
                <br><br><br><br><br><br><br>
            </div>
        </div>
    </div>
</div>




{% endblock content_block %}

templates/frontpage/frontpage.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load staticfiles %}

<!-- Header -->
{% block title %} Lapor Sis! {% endblock title %}
{% block navbar-active-home %}active{% endblock navbar-active-home %}


<!-- Body -->
{% block content_block %}
    <!-- <div class="container-fluid container-helloWorld d-flex align-items-center justify-content-center">
        <h1 class ="p-2" id="HelloWorld">Coming Soon!</h1>
    </div> -->

    <div class="container container-welcome-message d-flex col-12 ">
        <div class="row col-12 mx-auto my-5 p-4">
            <div class="container m-auto col-md-6">
                <div class="row mx-sm-3">
                    <h3 class="">Kamu tidak sendirian! Mari kita hentikan kekerasan bersama-sama, mulai dari kamu!</h3>
                </div>
                <div class="row mt-3 mx-sm-3">
                    <a href="{% url 'form:buatLaporan' %}" class="btn btn-dark button-pink mr-auto mx-sm-3">Buat Laporan</a>
                    <a href="{% url 'laporan:lihatLaporan' %}" class="btn btn-dark button-pink mx-2 mx-sm-3">Status Laporan</a>
                </div>
            </div>
            <div class="container m-auto col-md-6">
                <div class="row justify-content-center">
                    <div class="col-10">
                        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <div class="card my-4 my-md-0">
                                        <img src="{% static 'komnas-perempuan.jpg' %}" class="card-img-top mx-auto" style="width: 16em;">
                                        <div class="card-body">
                                            <p class="card-text">Selamat hari Anti kekerasan Terhadap perempuan! Kami berdiri untuk menegakkan keadilan</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="carousel-item">
                                    <div class="card">
                                        <img src="{% static 'three-smiling-orphans.jpg' %}" class="card-img-top mx-auto" alt="..." style="width: 23em;">
                                        <div class="card-body">
                                            <p class="card-text">Anak-anak pun butuh perlindungan! Mari kita dukung dengan mengingatkan terhadap sesama manusia</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="carousel-item">
                                    <div class="card">
                                        <img src="{% static 'lending-hands.png' %}" class="card-img-top" alt="">
                                        <div class="card-body">
                                            <p class="card-text">Keluarga Harmonis Tercipta dari kedamaian! ayo ciptakan Kedamaian</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                        </div>                    
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid container-fasilitas d-flex flex-column align-items-center justify-content-center py-3">
        <h1>Kita Bisa Bantu Kamu!</h1>
        <div class="container row py-2 d-flex justify-content-center ">

            <div class="card mx-auto my-3 my-sm-0" style="width: 18rem;">
                <img class="card-img-top mx-auto" src="{% static 'counselling.png' %}" alt="Card image cap" style="width: 16rem;">
                <div class="card-body">
                  <h5 class="card-title text-center">Konseling Trauma</h5>  
                  <p class="card-text text-justify">Lapor-sis menyediakan fasilitas bagi kalian yang menghadapi trauma. Agar, bisa kembali ke kehidupan yang damai</p>
                </div>
            </div>
            
            <div class="card mx-auto my-3 my-sm-0" style="width: 18rem;">
                <img class="card-img-top mx-auto my-2" src="{% static 'law.png' %}" alt="Card image cap" style="width: 10rem;">
                <div class="card-body">
                  <h5 class="card-title text-center">Bantuan Hukum</h5>
                  <p class="card-text text-justify">Bantuan Hukum akan diberikan bagi yang ingin menegakkan keadilan! Lapor-sis menyediakan layanan bagi kalian yang ingin keadilan</p>
                </div>
            </div>
            
            <div class="card mx-auto my-3 my-sm-0" style="width: 18rem;">
                <img class="card-img-top mx-auto" src="{% static 'shield.png' %}" alt="Card image cap" style="width: 10rem;">
                <div class="card-body">
                  <h5 class="card-title text-center">Perlindungan</h5>
                  <p class="card-text text-justify">Kami akan selalu memperjuangkan keadilan serta memberi perlindungan kepada korban    </p>
                </div>
            </div>
        </div> 
    </div>

    <div class="container-fluid container-statistik d-flex flex-column align-items-center py-3 col-12">
        <h1>Berapa Orang Yang Telah Kita Bantu?</h1>
        <div class="container container-statistic-card d-flex flex-wrap justify-content-around">
            
            <div class="card col-sm-5 mx-2 my-4" style="max-width: 540px;">
                <div class="row no-gutters"> 
                    <div class="col-4 my-auto">
                        <h1 id="angka-statistik" class="text-center">5624</h1>
                    </div>   
                    <div class="col-8">
                        <div class="card-body">
                            <h5 class="card-body"  class="text-center">Kasus KDRT</h5>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="card col-sm-5 mx-2 my-4" style="max-width: 540px;">
                <div class="row no-gutters"> 
                    <div class="col-4 my-auto">
                        <h1 id="angka-statistik"  class="text-center">4562</h1>
                    </div>   
                    <div class="col-8">
                        <div class="card-body">
                            <h5 class="card-body">Kasus Pemerkosaan</h5>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="card col-sm-5 mx-2 my-4" style="max-width: 540px;">
                <div class="row no-gutters"> 
                    <div class="col-4 my-auto">
                        <h1 id="angka-statistik"  class="text-center">4524</h1>
                    </div>   
                    <div class="col-8">
                        <div class="card-body">
                            <h5 class="card-body">Kasus Perselingkuhan</h5>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="card col-sm-5 mx-2 my-4" style="max-width: 540px;">
                <div class="row no-gutters"> 
                    <div class="col-4 my-auto">
                        <h1 id="angka-statistik"  class="text-center">1534</h1>
                    </div>   
                    <div class="col-8">
                        <div class="card-body">
                            <h5 class="card-body">Kasus Pelecehan</h5>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="card col-sm-5 mx-2 my-4" style="max-width: 540px;">
                <div class="row no-gutters"> 
                    <div class="col-4 my-auto">
                        <h1 id="angka-statistik"  class="text-center">9875</h1>
                    </div>   
                    <div class="col-8">
                        <div class="card-body">
                            <h5 class="card-body">Kasus Penelantaran Anak</h5>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="card col-sm-5 mx-2 my-4" style="max-width: 540px;">
                <div class="row no-gutters"> 
                    <div class="col-4 my-auto">
                        <h1 id="angka-statistik"  class="text-center">1234</h1>
                    </div>   
                    <div class="col-8">
                        <div class="card-body">
                            <h5 class="card-body">Kasus Stalking</h5>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="container-fluid container-footer h-30 pt-4 pb-4">
        <h1>Kenali Kami Lebih Baik</h1>
        <a href="{% url 'about:about' %}" class="btn btn-dark mt-3">Tentang Kami</a>
    </div>
    
{% endblock content_block %}

templates/frontpage/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load staticfiles %}

<!-- Header -->
{% block title %} Lapor Sis! {% endblock title %}

<!-- Body -->
{% block content_block %}
    <!-- <div class="container-fluid container-helloWorld d-flex align-items-center justify-content-center">
        <h1 class ="p-2" id="HelloWorld">Coming Soon!</h1>
    </div> -->
    <div class="container-fluid container-login-page d-flex align-items-center col-12 justify-content-center">
        <div class=" container row col-4">
            <h1 id="header-login-page">Login</h1>
            <div class="container container-login border border-secondary rounded-lg">
                <form action="POST">
                    {{form}}
                    <a  class="btn btn-danger btn-sm align-middle" href="{% url 'jadwalku:delete' kegiatan.id %}">delete</a>
                </form>
            </div>
        </div>
    </div>
    

   
{% endblock content_block %}

templates/frontpage/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load staticfiles %}

<!-- Header -->
{% block title %} Lapor Sis! {% endblock title %}
{% block navbar-active-home %}active{% endblock navbar-active-home %}


<!-- Body -->
{% block content_block %}
    <!-- <div class="container-fluid container-helloWorld d-flex align-items-center justify-content-center">
        <h1 class ="p-2" id="HelloWorld">Coming Soon!</h1>
    </div> -->
    <div class="container-fluid container-login-page d-flex align-items-center col-12 justify-content-center">
        <div class=" container row col-4 justify-content-center">
            <h1 id="header-login-page">Register Newsletter</h1>
            <div class="container container-login border border-secondary rounded-lg">
                    <form action="{% url 'frontpage:register' %}" method="POST">
                        {%csrf_token%}
                        {{form.as_p}}
                        <input type="submit" class="btn btn-primary" value="Daftar" style="float: right;">
                    </form>
                    <br>
                    <br>
                    <br>
                    <p>Are you admin?</p>
                    <a href="{% url 'laporan:ubahLaporan'%}" class="btn btn-danger mb-5"> click me to chage status</a>
            </div>
        </div>
    </div>
    

   
{% endblock content_block %}

templates/laporan/ubah_laporan.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block content_block %}
<div id="ubah_laporan">
    <div class="container">
        <br>
        <h1 class="judul">{{ title }}</h1>
        <br>
        <div>
            <table class="table" id="table_ubah_laporan">
                <thead class="thead-light">
                  <tr>
                    <th class="text-center" style="width: 22%" scope="col">Nama</th>
                    <th class="text-center" style="width: 20%" scope="col">Kategori</th>
                    <th class="text-center" style="width: 23%" scope="col">Status</th>
                    <th style="width: 35%" scope="col"></th>
                  </tr>
                </thead>
                <tbody>
                    {% for jawaban in respon %}
                    <tr>
                        <td class="text-center">{{jawaban.nama}}</td>
                        <td class="text-center">Pencurian</td>
                        <td>
                          <form method="POST" action="{% url 'laporan:ubahStatusLaporan' id=jawaban.id %}">
                            {% csrf_token %}
                            {{lapor.as_p}}
                            <button type="submit" class="btn btn-primary waves-effect waves-light" value="Save">Ubah Status</button>
                          </form>
                        </td>
                        <td class="text-center"><p>
                            <button id="detail_button" class="btn btn-light button-pink" type="button" data-toggle="collapse" data-target="#collapseExample{{ forloop.counter }}" aria-expanded="false" aria-controls="collapseExample">
                              Details
                            </button>
                          </p>
                          <div class="collapse" id="collapseExample{{ forloop.counter }}">
                            <div class="card card-body">
                              <div class="text-justify"> 
                                {{jawaban.laporan}} 
                              </div>
                            </div>
                          </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    
</div>
{% endblock content_block %}